name: Learn GitHub Actions

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "✅ GitHub Actions가 잘 동작합니다!"

